//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.XPButtonTest {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Images {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Images() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.XPButtonTest.Images", typeof(Images).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		internal static System.Drawing.Bitmap _Paste {
			get {
				object obj = ResourceManager.GetObject("_Paste", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _Save {
			get {
				object obj = ResourceManager.GetObject("_Save", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap buttonXP1_Image {
			get {
				object obj = ResourceManager.GetObject("buttonXP1.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap buttonXP2_Image {
			get {
				object obj = ResourceManager.GetObject("buttonXP2.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Icon Icon {
			get {
				object obj = ResourceManager.GetObject("Icon", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap Paste0 {
			get {
				object obj = ResourceManager.GetObject("Paste0", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap Paste1 {
			get {
				object obj = ResourceManager.GetObject("Paste1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap Paste2 {
			get {
				object obj = ResourceManager.GetObject("Paste2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap Save0 {
			get {
				object obj = ResourceManager.GetObject("Save0", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap Save2 {
			get {
				object obj = ResourceManager.GetObject("Save2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
